#ifndef ERROR_H
#define ERROR_H
typedef enum{
    ERROR_OK = 0,
    /* System error */
    ERROR_MEMORY_REALLOCATE,
    ERROR_INVALID_POINTER,
    ERROR_CONNET_DB,
    ERROR_OUTPUT_FILE,
    ERROR_ACCOUNT_INVENTORY_MISMATCH,
    ERROR_INVALID_TYPE,
    /* Account Errors */
    ERROR_INVALID_ARGUMENT,
    ERROR_INSUFFENT_SAVING,
    ERROR_INVALID_TRANSCATION_TYPE,
    ERROR_EXCEED_CREDIT_LIMITATION,
    ERROR_INVLID_ACCOUNT_UPDATE,
    ERROR_INSUFFENT_ACCOUNT_QUANTITY,
    /* Inventory error */
    ERROR_INSUFFENT_INVENTORY,
    ERROR_INVALID_SN,
    ERROR_EXPAND_FAILED,
    ERROR_ALREADY_EXISTS,
    ERROR_ALREADY_NOEXISTS,
    ERROR_INVLID_INV_UPDATE,
    ERROR_ROLLBACK_OK,
    ERROR_ROLLBACK_WRONG,
    ERROR_WRONG,
} ErrorCode;
#endif
