#ifndef ERROR_H
#define ERROR_H
typedef enum{
    ERROR_OK = 0,
    /* System error */
    ERROR_MEMORY_REALLOCATE,
    ERROR_INVALID_POINTER,
    ERROR_CONNET_DB,
    ERROR_OUTPUT_FILE,
    /* Normal error */
    ERROR_INVALID_ARGUMENT,
    ERROR_INVALID_TYPE,
    ERROR_INVALID_SYMBOL,
    ERROR_NOT_FOUND,
    ERROR_ALREADY_EXISTS,
    ERROR_EXPAND_FAILED,
    ERROR_UNKNOWN,
    ERROR_ROLLBACK_WRONG,
    /* Inventory error */
    ERROR_INSUFFICIENT_INVENTORY,
    ERROR_INVALID_INVENTORY_UPDATE,
    /* Account Errors */
    ERROR_INSUFFICIENT_SAVING,
    ERROR_INVALID_TRANSCATION_TYPE,
    ERROR_EXCEED_CREDIT_LIMITATION,
    ERROR_INVALID_ACCOUNT_UPDATE,
    ERROR_INSUFFENT_ACCOUNT_QUANTITY,
    ERROR_ACCOUNT_INVENTORY_MISMATCH,
    /* Customer Errors */
    ERROR_ACCOUNT_CREATED,


} ErrorCode;
#endif
